name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Version/commit SHA to rollback to'
        required: true
        type: string

jobs:
  rollback:
    name: Rollback ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.version }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        CI: true
        GENERATE_SOURCEMAP: false
    
    - name: Perform rollback
      run: |
        echo "Rolling back ${{ github.event.inputs.environment }} to version ${{ github.event.inputs.version }}"
        # Add rollback script here based on your deployment platform
        
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "Rolling back production..."
          # Production rollback commands
        else
          echo "Rolling back staging..."
          # Staging rollback commands
        fi
    
    - name: Verify rollback
      run: |
        echo "Verifying rollback..."
        # Add verification tests here
    
    - name: Notify team
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Rollback of ${{ github.event.inputs.environment }} to ${{ github.event.inputs.version }} - ${{ job.status }}'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      continue-on-error: true